### ISSUE TITLE
model check points download address is invalid

### ISSUE THREAD

**Issue by shawinbetter** [jas-preet/SPOT-1D-Single#2]
The address of model checkpoints https://servers.sparks-lab.org/downloads/jits.tar.xz is invalid.

**Comment by honestAnt** [comment]
try this：https://apisz.sparks-lab.org:8443/downloads/Resource/Protein/2_Protein_local_structure_prediction/jits.tar.xz

**Comment by lhm-sunshine** [comment]
> 把这个权重放在和代码一起的文件夹里吗

**Comment by jas-preet** [comment]
He download link has been updated, I hope you will be available to download that now. Apologies for delayed response as I do not regularly update or maintain Github due to very limited availability. Additionally thank you to the members of community for responding questions.
